### ISSUE TITLE
Falsche Zusammenhänge von Zusammenhangsbegriffe

### ISSUE THREAD

**Issue by timjb** [GraffL/Man-sieht-leicht...#1]
Ich finde deine Übersicht zu den Zusammenhängen der Zusammenhangsbegriffe ziemlich cool!

Ich habe zwei Fehler und ein fehlendes Gegenbeispiel gefunden:

* Die Implikationen zwischen "halb-lokal einfach zshgd" und "lokal einfach zshgd" sind genau falsch herum. Letzteres impliziert ersteres, aber nicht umgekehrt.
* Der Kegel C(H) auf den Hawaiianischen Ohrringen H ist ein Raum, der semi-lokal einfach zshgd, aber nicht lokal einfach zsghd ist, also ein Beispiel für die Nicht-Implikation aus Punkt eins.
* In der Interpretation von "halb-lokal einfach zshgd" sollte "zusammenziehbar" durch "einfach zshgd" ersetzt werden.  Ich fände aber passender: "Jede Schleife in einer Umgebung von x ist global trivial."

**Comment by GraffL** [comment]
Vielen Dank für die Anmerkungen - sollte jetzt verbessert sein.

Und viel Erfolg bei der Prüfung :-)
